FROM node:16.13.0-alpine as builder

WORKDIR /app

COPY . .

RUN npm ci

RUN npm run build

FROM node:16.13.0-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist

COPY package*.json /app/

RUN npm ci --only=production

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
