version: 2.1

jobs:
  test:
    docker:
      - image: node:14.17.0-alpine
    steps:
      - checkout
      - run:
          name: Set up
          command: |
            npm ci
      - run:
          name: Test coverage
          command: |
            npm run test:cov

  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: build image
          command: |
            echo $CIRCLE_SHA1
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -f ./docker/app/Dockerfile.prod -t 20160190/api-example:$CIRCLE_SHA1 .
            docker push 20160190/api-example:$CIRCLE_SHA1

workflows:
  ci_test:
    jobs:
      - test
      - build
