version: 2.1

jobs:
  test:
    docker:
      - image: node:14.17.0-alpine
    steps:
      - checkout
      - run:
          name: Set up
          command: |
            npm ci
      - run:
          name: Test coverage
          command: |
            npm run test:cov

  build:
    docker:
      - image: docker:latest
      - image: docker:dind
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for docker:dind
          command: dockerize -wait tcp://localhost:2375 -timeout 1m
      - run:
          name: build image
          command: |
            docker build -f ./docker/app/Dockerfile.prod -t 20160190/api-example .

workflows:
  ci_test:
    jobs:
      - test
      - build
