version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  test:
    docker:
      - image: node:14.17.0-alpine
    steps:
      - checkout
      - run:
          name: Set up
          command: |
            npm ci
      - run:
          name: Test coverage
          command: |
            npm run test:cov

workflows:
  ci_test:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: "hugo-test"
          tag: "$CIRCLE_SHA1"
          aws-access-key-id: "$AWS_ACCESS_KEY_ID"
          aws-secret-access-key: "$AWS_SECRET_ACCESS_KEY"
          create-repo: true
          context: .
          dockerfile: "Dockerfile.prod"
          path: "docker/app"
          region: $AWS_REGION
          requires:
            - test
