version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  test:
    docker:
      - image: node:14.17.0-alpine
    steps:
      - checkout
      - run:
          name: Set up
          command: |
            npm ci
      - run:
          name: Test coverage
          command: |
            npm run test:cov

  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - aws-cli/install
      - aws-cli/setup
      - run:
          name: Create ECR repo if missing
          command: |
            export AWS_ECR_CREATE_REPO_RESPONSE=$(aws ecr create-repository --repository-name hugo-test --image-scanning-configuration scanOnPush=true 2>&1)
            echo $AWS_ECR_CREATE_REPO_RESPONSE
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -f ./docker/app/Dockerfile.prod -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/hugo-test:$CIRCLE_SHA1 .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/hugo-test:$CIRCLE_SHA1

workflows:
  ci_test:
    jobs:
      - test
      - build
