version: 2.1

jobs:
  test:
    docker:
      - image: node:14.17.0-alpine
    steps:
      - run:
          name: Set up
          command: |
            npm ci
      - run:
          name: Test coverage
          command: |
            npm run test:cov
