apiVersion: v1
kind: Secret
metadata:
    name: api-example
stringData:
    DRAFT: ENC[AES256_GCM,data:7Vfn+iw=,iv:AsLkAc2jVFBpLIx5c4OwazJvZAL+VGUP5N4y8KNfUPk=,tag:j/ASwrhwLBnLZ75JJjwkfw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-southeast-1:074883510775:key/d72a753f-47dd-463a-8c9d-7001a1ab6b91
          created_at: "2021-11-27T17:48:39Z"
          enc: AQICAHgn6fvh+r/rWqYhsis33jCoRW2B8d0RblMiDA0KiL6fsgH90jqxRUMzVn27jRjEhOElAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMD2DPZQ6B57fiGcaiAgEQgDv6ul+oaeGf/PXNh7qE6hxwiJy1lCmhINIGMv7/JZ8hO6mWmPG7RMcZLlUEgHpDJrV6s4tf4/fJ/1FWlg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-27T17:48:39Z"
    mac: ENC[AES256_GCM,data:wbHCWoGkxvVYS9irgNnC0eBl7vZbSdlMhAOUil/JJnjCJW0dC6Dc9LQg7LfdjYM2ZhIMi2DPpqmLT/LXdTdL6+GtuFiNnBVi0A0wqKejlsVgs7XDkbVpaEuIKtRK/tPpUxmXvkuMtX6sJ/kbaAekRQIkaX55kvXltmnaG2/0tbo=,iv:RqrvDwO/RcTbPbwS6oLI8/JhkqoCnqM996MQLfnhwyA=,tag:tGhlmCIGPDE4YMzcwAbzYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
