name: Example test

on: [push]

jobs:
  checkout_another_repo:
    runs-on: ubuntu-20.04
    env:
      KUBECL_VERSION: 1.20.0
      HELM_VERSION: 3.0.0
    steps:
      - name: Set up base
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          sudo wget -q https://storage.googleapis.com/kubernetes-release/release/v${KUBECL_VERSION}/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl
          sudo chmod +x /usr/local/bin/kubectl
          kubectl version --client
          sudo wget -q https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
          sudo chmod +x /usr/local/bin/helm
          helm version
          curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
          chmod +x ./aws-iam-authenticator
          sudo mv aws-iam-authenticator /usr/local/bin/
          aws-iam-authenticator --help
      - name: clone another repo
        uses: actions/checkout@v2
        with:
          repository: 'anhnt160190/draft-sdk'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Set up Kube Config
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Try test
        run: kubectl version --client
      - name: Try test 2
        run: kubectl cluster-info
