name: Example test

on: [push]

jobs:
  checkout_another_repo:
    runs-on: ubuntu-20.04
    steps:
      - name: clone another repo
        uses: actions/checkout@v2
        with:
          repository: 'anhnt160190/draft-sdk'
      - name: Test
        run: |
          echo "Test"
          echo $GITHUB_SHA
          ls