name: CI CD for api-example

on:
  push:
    branches:
      - master
      - develop
      - 'releases/**'
      - 'feature/**'
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.0
      - run: npm ci
      - run: npm run test:cov

  build:
    needs: ['test']
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push to Docker Hub
        env:
          DOCKER_REPOSITORY: 20160190/api-example
        run: |
          echo "Start Build Docker Image"
          export IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")
          docker build -f ./docker/app/Dockerfile.prod -t ${DOCKER_REPOSITORY}:${IMAGE_TAG} .
          docker push ${DOCKER_REPOSITORY}:${IMAGE_TAG}
